---
title: "Complex data - project"
author: "Stanisław Wilczyński, Anna Zaleska"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(results = 'asis');
options(xtable.comment=FALSE)
library(PBImisc)
library(xtable)
library(lattice)
library(lme4)
library(nlme)
#library(lmerTest)

data(kidney)
```


```{r}

xy_kidney <- reshape(kidney[1:15,], direction = "long", varying = list(9:16), v.names = c("MDRD"), times = c(1/4,1,3,6,12,24,36,60))
lkidney$ltime <- log(lkidney$time)

xyplot(MDRD ~ time | id, xy_kidney, type=c("g","p","r"), xlab = "time since transplant", ylab = "MDRD", pch=19)
xyplot(MDRD ~ ltime | id, xy_kidney, type=c("g","p","r"), xlab = "log(time since transplant)", ylab = "MDRD", pch=19)

lkidney <- reshape(kidney, direction = "long", varying = list(9:16), v.names = c("MDRD"), times = c(1/4,1,3,6,12,24,36,60))
lkidney$ltime <- log(lkidney$time)

```


### Analiza bez efektów losowych (Stachu)
```{r}
attach(lkidney)
detach(lkidney)
```

```{r}
for(i in 1:8){
  model.variable <- lm(MDRD ~ lkidney[,i], data = lkidney)
  print(paste("Model for", colnames(lkidney)[i]))
  print(summary(model.variable))
  print("---------------------------------------------------------------------------")
  #donor.age, CIT, discrepanacy.DR
}
```




```{r}
un.model.reml <- gls(MDRD~factor(time)*(donor.age+bpl.drugs+recipient.age+discrepancy.AB+diabetes+discrepancy.DR+CIT+therapy),
correlation=corSymm(form= ~1 | id),
weights=varIdent(form= ~1 | time),
data=lkidney)

cs.model.reml <- gls(MDRD~factor(time)*(donor.age+bpl.drugs+recipient.age+discrepancy.AB+diabetes+discrepancy.DR+CIT+therapy),
correlation=corCompSymm(form= ~1 | id),
weights=varIdent(form= ~1),
data=lkidney)

ar.model.reml <- gls(MDRD~factor(time)*(donor.age+bpl.drugs+recipient.age+discrepancy.AB+diabetes+discrepancy.DR+CIT+therapy),
correlation=corAR1(form= ~1 | id),
weights=varIdent(form= ~1),
data=lkidney)

car.model.reml <- gls(MDRD~factor(time)*(donor.age+bpl.drugs+recipient.age+discrepancy.AB+diabetes+discrepancy.DR+CIT+therapy),
correlation=corCAR1(form= ~ltime | id),
data=lkidney)

```


```{r}
covar <- getVarCov(un.model)
anova(un.model.reml,ar.model.reml, cs.model.reml, car.model.reml)
print(covar)
```
```{r}
un.model <- gls(MDRD~factor(time)*(donor.age+bpl.drugs+recipient.age+discrepancy.AB+diabetes+discrepancy.DR+CIT+therapy),
correlation=corSymm(form= ~1 | id),
weights=varIdent(form= ~1 | time),
data=lkidney, method = "ML")

un.model.no.int <- gls(MDRD~factor(time)+(donor.age+bpl.drugs+recipient.age+discrepancy.AB+diabetes+discrepancy.DR+CIT+therapy),
correlation=corSymm(form= ~1 | id),
weights=varIdent(form= ~1 | time),
data=lkidney, method = "ML")

quad.model <- gls(MDRD~(ltime + I(ltime^2))*(donor.age+bpl.drugs+recipient.age+discrepancy.AB+diabetes+discrepancy.DR+CIT+therapy),
correlation=corSymm(form= ~1 | id),
weights=varIdent(form= ~1 | time),
data=lkidney, method = "ML")

lin.model <- gls(MDRD~ltime*(donor.age+bpl.drugs+recipient.age+discrepancy.AB+diabetes+discrepancy.DR+CIT+therapy),
correlation=corSymm(form= ~1 | id),
weights=varIdent(form= ~1 | time),
data=lkidney, method = "ML")
```


```{r}
anova(quad.model, un.model)
anova(quad.model, lin.model)
anova(un.model, lin.model)
anova(un.model.no.int, un.model)
anova(un.model)
```

```{r}
simpler.un.model <- gls(MDRD~factor(time)*(donor.age+bpl.drugs+diabetes+therapy),
correlation=corSymm(form= ~1 | id),
weights=varIdent(form= ~1 | time),
data=lkidney, method = "ML")

simpler.un.model2 <- gls(MDRD~factor(time)*(donor.age+bpl.drugs),
correlation=corSymm(form= ~1 | id),
weights=varIdent(form= ~1 | time),
data=lkidney, method = "ML")

```

```{r}
anova(un.model, simpler.un.model2, simpler.un.model)
```

```{r}
simpler.un.model.no.int <- gls(MDRD~factor(time)+(donor.age+bpl.drugs),
correlation=corSymm(form= ~1 | id),
weights=varIdent(form= ~1 | time),
data=lkidney, method = "ML")

simpler.un.model.lin <- gls(MDRD~ltime+donor.age+bpl.drugs,
correlation=corSymm(form= ~1 | id),
weights=varIdent(form= ~1 | time),
data=lkidney, method = "ML")

simpler.un.model.quad <- gls(MDRD~ltime+I(ltime^2)+donor.age+bpl.drugs,
correlation=corSymm(form= ~1 | id),
weights=varIdent(form= ~1 | time),
data=lkidney, method = "ML")
```

```{r}
anova(un.model, simpler.un.model.no.int, simpler.un.model.lin, simpler.un.model.quad)
```



### Ania



```{r}

const.mixed.model <- lmer(MDRD~ltime+(1|id),
                         data = lkidney, REML = FALSE)
summary(const.mixed.model)

const.mixed.model2 <- lme(MDRD~ltime, random =~1|factor(id),
                         data = lkidney, method = "ML")
summary(const.mixed.model2)
```



```{r}
lin.mixed.model <- lmer(MDRD~ltime+ (ltime|id),
                         data = lkidney, REML = FALSE)
summary(lin.mixed.model)
lin.mixed.model2 <- lme(MDRD~ltime, random =~ltime|factor(id),
                         data = lkidney, method = "ML")
summary(lin.mixed.model2)
```


```{r}

quadr.mixed.model <- lmer(MDRD~ltime + I(ltime^2) + (ltime + I(ltime^2)|id),
                         data = lkidney, REML = FALSE)
summary(quadr.mixed.model)
quadr.mixed.model2 <- lme(MDRD~ltime + I(ltime^2), random =~ltime + I(ltime^2)|factor(id),
                         data = lkidney, method = "ML")
summary(quadr.mixed.model2) 

```


```{r}
anova(const.mixed.model,lin.mixed.model,quadr.mixed.model)
```


```{r}
anova(const.mixed.model2,lin.mixed.model2,quadr.mixed.model2)
```

```{r}
full.model <- lmer(MDRD~donor.age + recipient.age + therapy + diabetes + bpl.drugs + discrepancy.AB + discrepancy.DR + ltime + I(ltime^2) + (ltime + I(ltime^2)|id), data = lkidney, REML = FALSE)
summary(full.model)

full.model2 <- lme(MDRD~donor.age + recipient.age + therapy + diabetes + bpl.drugs + discrepancy.AB + discrepancy.DR + ltime + I(ltime^2)  , random =~ltime + I(ltime^2)|factor(id), data = lkidney,  method = "ML")
summary(full.model2)
```

```{r}
anova(full.model2)
```

```{r}
final.model <- lme(MDRD~donor.age + bpl.drugs + ltime + I(ltime^2)  , random =~ltime + I(ltime^2)|factor(id), data = lkidney,  method = "ML")
final.model2 <- lme(MDRD~donor.age + therapy +  bpl.drugs + ltime + I(ltime^2)  , random =~ltime + I(ltime^2)|factor(id), data = lkidney,  method = "ML")
anova(final.model, final.model2)
```


```{r}
library(car)
qqPlot(ranef(final.model2)[,1], envelope = FALSE, ylab = expression(a[i]))
qqPlot(ranef(final.model2)[,1], envelope = FALSE, ylab = expression(b[i]))
qqPlot(ranef(final.model2)[,1], envelope = FALSE, ylab = expression(c[i]))
```


```{r}
ranef(final.model2)[,1]
```




