---
title: "Complex Data - lab1"
author: "Stanisław Wilczyński"
date: "8 maja 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Tak1


```{r cars}
lead <- read.table(file = "../data/lead.txt", header = FALSE)
names(lead) <- c("id", "baseline", paste("week", c(1,4,6), sep=""))
summary(lead)
```

```{r}
mean.y <- apply(lead[,2:5], 2, mean)
print(mean.y)
sd.y <- apply(lead[,2:5], 2, sd)
print(sd.y)
apply(lead[,2:5], 2, summary)
```

```{r}
library(reshape2)
lead.uni <- melt(lead, id.vars = c("id"), value.name = "y")
lead.uni <- lead.uni[c(1,3)]
lead.uni <- lead.uni[order(lead.uni$id),]
lead.uni$time <- rep(c(0,1,4,6))
lead.uni$time.cat <- rep(1:4)
head(lead.uni)
```
```{r}
library(nlme)
lead.cat <- gls(y~factor(time.cat),
correlation=corSymm(form= ~1 | id),
weights=varIdent(form= ~1 | factor(time.cat)),
data=lead.uni)
summary(lead.cat)
```
1. Reml unstrutured
```{r}
covariance.matrix <- getVarCov(lead.cat)
print(covariance.matrix)
```

Covariance matrices are different because of sigma_11 - residual standard error.
task 1 - var(Y) or var(Y|X)
task 3 - what can we assume (maybe the same variances, correlations)
task 6 - use a test

2. ML unstructured
```{r}
lead.cat.ml <- gls(y~factor(time.cat),
correlation=corSymm(form= ~1 | id),
weights=varIdent(form= ~1 | factor(time.cat)),
data=lead.uni, method = "ML")
summary(lead.cat.ml)
covariance.matrix.ml <- getVarCov(lead.cat.ml)
print(covariance.matrix.ml)
```
```{r}

```
3 i 4.
Sprawdzimy tą samą wariancję

```{r}
lead.cat.ident.var <- gls(y~factor(time.cat),
correlation=corSymm(form= ~1 | id),
weights=varIdent(),
data=lead.uni)
print(getVarCov(lead.cat.ident.var))
```


```{r}
anova(lead.cat.ident.var, lead.cat)
```
```{r}
anova(lead.cat, lead.cat.ident.var)
```
Do rozkminy: jak działa ta cudna funkcja, co wybrać na rozsądne założenia o macierzy kowariancji

5. 

```{r}
intervs <- intervals(lead.cat)$coef
for(i in 2:4){
  intervs[i,] <- intervs[i,] + intervs[1,]
}
#print(intervs)
intervs <- as.data.frame(intervs)
#print(intervs)


lmod <- lm(y~factor(time.cat), data = lead.uni)
intervs_lm <- confint(lmod)
for(i in 2:4){
  intervs_lm[i,] <- intervs_lm[i,] + intervs_lm[1,]
}
print(intervs_lm)
```
```{r}

library(ggplot2)
ggplot(intervs, aes(x=c(0,1,2,3), y=intervs$est)) + 
    geom_errorbar(aes(ymin=intervs$lower, ymax=intervs$upper, color="red"), width=.1) +
    geom_errorbar(aes(ymin=intervs_lm[,1], ymax=intervs_lm[,2]), width=.1) +
    geom_line() +
    geom_point()
```
```{r}
print(intervs)
intervs$type <- "gls"
colnames(intervs) <- c("lower", "mean", "upper", "type")
intervs_lm <- as.data.frame(intervs_lm)
intervs_lm[,3] <- intervs[,2]
intervs_lm[,4] <- "lm"
intervs_lm <- intervs_lm[,c(1,3,2,4)]
colnames(intervs_lm) <- c("lower", "mean", "upper", "type")
```


```{r}
intervs_plot <- rbind(intervs, intervs_lm)
intervs_plot$time <- seq(c(1,2,3,4))

pd <- position_dodge(0.1)
ggplot(intervs_plot, aes(x=intervs_plot$time, y=intervs_plot$mean, color = intervs_plot$type)) +
    geom_errorbar(aes(ymin=intervs_plot$lower, ymax=intervs_plot$upper), width=.1, position = pd) +
    geom_line(position = pd) +
    geom_point(position = pd)
```
6. Co to za test?
```{r}
anova(lead.cat, c(0,1,-1,0))
```

