---
title: "Complex Data - lab5"
author: "Stanisław Wilczyński"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ALA)
library(latex2exp)
library(ggplot2)
library(reshape2)
library(nlme)
library(lattice)
library(magrittr)
library(knitr)
library(kableExtra)
library(gee)
library(lme4)
```

## Questions before exercises:

* What patterns do you notice?(p.1)
* What do we conclude about changes in the log odds of obesity over time for boys and girls?(p.5)


```{r}
musc.dat <- read.table("../data/muscatine.txt",na.strings=".", as.is=T)
names(musc.dat) <- c("id", "gender", "baseage", "age", "occasion", "y")
musc.dat$cage <- musc.dat$age - 12
```


```{r, include=FALSE}
## Model fit
musc.gee <- gee(y~gender*cage + gender*I(cage^2),
  id=id,
  family="binomial",
  data=musc.dat,
  corstr="unstructured")
## Summary of the output
summary(musc.gee)
```

```{r}
## Model fit
musc.gee.noInt <- gee(y~gender + cage + I(cage^2),
id=id,
family="binomial",
data=musc.dat,
corstr="unstructured")
## Summary of the output
summary(musc.gee.noInt)
```


```{r}
## predictions
musc.sel.dat <- matrix(unlist(expand.grid(unique(musc.dat$gender),
unique(musc.dat$cage))), ncol=2)
musc.sel.dat <- cbind(rep(1,dim(musc.sel.dat)[1]),
musc.sel.dat, musc.sel.dat[,2]^2)
colnames(musc.sel.dat) <- c("Int", "gender","cage", "cage2")
musc.lin.pred <- musc.sel.dat %*% matrix(coef(musc.gee.noInt), ncol=1)
musc.exp.pred <- exp(musc.lin.pred)/(1+exp(musc.lin.pred))
musc.all.pred <- cbind(musc.sel.dat, musc.lin.pred, musc.exp.pred)
```

```{r}
depress.dat <- read.table("../data/depress.txt",na.strings=".")
names(depress.dat) <- c("id", "y", "severe", "drug", "time")
dim(depress.dat)
depress.gee <- gee(y~severe + drug*time,
  id=id,
  family="binomial",
  data=depress.dat,
  corstr="unstructured")
summary(depress.gee)
```


```{r}
## GLMM
depress.glmer <- glmer(y ~ severe + drug*time + (1|id),
family = binomial,
data=depress.dat)
summary(depress.glmer)
```

